name: Unity Test Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  run-tests:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate secret script
        run: |
            cp Assets/RegularGame/Scripts/DataBase/Secrets/SecretTemplate.cs Assets/RegularGame/Scripts/DataBase/Secrets/Secret.cs
            sed -i 's/#YOURSECRETKEY#/${{ secrets.DB_KEY }}/g' Assets/RegularGame/Scripts/DataBase/Secrets/Secret.cs
            sed -i 's/#YOURSAVESCOREURL#/${{ secrets.DB_SAVESCORE_URL }}/g' Assets/RegularGame/Scripts/DataBase/Secrets/Secret.cs
            sed -i 's/#YOURGETTOPSCORESURL#/${{ secrets.DB_GETTOPSCORE_URL }}/g' Assets/RegularGame/Scripts/DataBase/Secrets/Secret.cs
      - name: Run Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./ 
          testMode: all
          unityVersion: 6000.0.60f1
